### ISSUE TITLE
Import single modules whenever is possible

### ISSUE THREAD

**Issue by gcanti** [OliverJAsh/twitter-api-ts#1]
`fp-ts` modules are supposed to be imported one by one

```
import * as foo from 'fp-ts/lib/Foo'
```

otherwise you end up with an unwanted heavy bundle.

Example in `types.ts`

```diff
-import { either, option } from 'fp-ts';
+import * as either from 'fp-ts/lib/Either'
+import * as option from 'fp-ts/lib/Option'
```

**Comment by OliverJAsh** [comment]
Thanks, fixed in https://github.com/OliverJAsh/twitter-api-ts/commit/8947aaefe6a4d9c7218f5c74a9812cebdd238ddf.
