### ISSUE TITLE
Enum declaration error in Constants.d.ts

### ISSUE THREAD

**Issue by deshmukhshivkumar** [OliverJAsh/twitter-api-ts#3]
Hey,
I am facing this error.
Line number 4
_In ambient enum declarations member initializer must be constant expression._

**Comment by OliverJAsh** [comment]
What version of TypeScript are you using? String enums are only supported in TS 2.4.

**Comment by deshmukhshivkumar** [comment]
Ohh, I am using version  1.8. 
Thanks.
